# Don't forget to run
#
#     pkg> dev ..
#
[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
MyModule = "d18defe2-ea8b-5af7-8ee9-e42adac5e2de"

[compat]
Documenter = "1"
